### ISSUE TITLE
Why does this require jquery?

### ISSUE THREAD

**Issue by sgup** [imagekit-developer/imagekit-javascript#1]
I'm trying to use this with a modern react app, which doesn't require jQuery at all. Surely the ajax calls could be replaced in this library with vanilla js calls?

**Comment by manu4543** [comment]
Yes. We will release a new version without jQuery dependency.

**Comment by imagekitio** [comment]
Hi Shridhar,

A new version (1.0.1) of ImageKit.io javascript SDK has been released which
doesn't depend on jQuery.

Please install the latest version using npm or directly from
https://github.com/imagekit-developer/imagekit-javascript

Best regards,

[image: ImageKit.io]
https://imagekit.io <http://imagekit.io/>

Follow us:
<https://www.linkedin.com/company/imagekit> <https://twitter.com/imagekitio>
<https://www.facebook.com/imagekit.io>
*Manu Chaudhary*
Co-founder & CIO | ImageKit.io
E: manu@imagekit.io | M: +91-8826055223
Linkedin: manu4543 <https://www.linkedin.com/in/manu4543/>
Skype: manu4543
IMPORTANT: The contents of this email and any attachments are confidential.
It is strictly forbidden to share any part of this message with any third
party, without the written consent of the sender. If you received this
message by mistake, please reply to this message and follow with its
deletion, so that we can ensure such a mistake does not occur in the future.


ᐧ
