### ISSUE TITLE
No TypeScript definitions this day and age?

### ISSUE THREAD

**Issue by kevinclarkadstech** [imagekit-developer/imagekit-javascript#26]
That is a dealbreaker for me to use your service, even if it looks great.

**Comment by brunosmm** [comment]
Adding TS will facilitate a lot.

**Comment by imagekitio** [comment]
@brunosmm Contributions are welcome :) We won't be working on adding TS in the next couple of months.

**Comment by brunosmm** [comment]
@imagekitio contribution added, it's an adaptation from the types I created for my project based on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/08f078e1e0d3da2f2dde1a71fb8d66b71971413d/types/imagekit/ as reference.

Credits to @kemicofa and @romdim:
- Kevin Faulhaber <https://github.com/kemicofa>
- Romanos Tsouroplis <https://github.com/romdim>

**Comment by brunosmm** [comment]
Hey @imagekitio,
You asked for contributions but didn't even look at the PR... Do you really want contributions?

**Comment by kevinclarkadstech** [comment]
> Hey @imagekitio,
> 
> You asked for contributions but didn't even look at the PR... Do you really want contributions? 

This would make me livid. Striking this service out as one that I would EVER use. It's a commercial product, not open source.

**Comment by manu4543** [comment]
@brunosmm, I apologize for the confusion and delayed response. When I mentioned we wouldn't be able to add TS anytime in the coming months, it includes everything - finding the best way to do it, writing new code, reviewing PR, testing, and merging. I believe https://github.com/DefinitelyTyped/DefinitelyTyped would be the right place for you to make contributions. They actively work on adding new type definitions to existing repositories. So I will be closing this issue, as we won't adding TS definitions as part of this repo.

@kevinclarkadstech  Yes, it's a commercial product. We are always working hard to bring all our SDKs up to speed with the latest requirements and the features being requested in the product and appreciate the effort being put in by the dev community in helping us with the same. Unfortunately, this issue is not our priority at the moment. If lack of typescripts is a dealbreaker for you, you should go ahead with one of the other options for now.

**Comment by isaachinman** [comment]
@imagekitio Just want to mention that I briefly interacted with your product as a potential customer, and have been put off entirely by this issue.

It's one thing that you wouldn't add types for a commercial, paid-for product, but another that you aren't even writing your source in TypeScript in the first place.

Neither of those things inspire any sort of confidence in your product.

**Comment by kevinclarkadstech** [comment]
@imagekitio @manu4543  you guys must be small potatoes if you cannot even review a PR for months.  Another good reason not to inspire confidence @imagekitio @brunosmm .  I just went with Cloudinary.
